version: "3.8"
services:
  supervisor:
    platform: linux/amd64
    build:
      context: ./build
      args:
        # MODERNIZED: Defaults
        PYTHON_VERSION: ${PYTHON_VERSION:-3.12}
        PYTORCH_VERSION: ${PYTORCH_VERSION:-2.5.1}
        COMFYUI_BUILD_REF: ${COMFYUI_BUILD_REF:-}
        # MODERNIZED: Point to your Python Image
        IMAGE_BASE: ${IMAGE_BASE:-ghcr.io/phonehomephone/python:v2-cuda-12.8.1-py3.12-22.04}
      tags:
        # MODERNIZED: Your Registry and Tag Schema
        - "ghcr.io/phonehomephone/comfyui:${IMAGE_TAG:-v2-cuda-12.8.1-pytorch-2.5.1-py3.12-22.04}"
        
    image: ghcr.io/phonehomephone/comfyui:${IMAGE_TAG:-v2-cuda-12.8.1-pytorch-2.5.1-py3.12-22.04}
    
    ## For Nvidia GPU's - You probably want to uncomment this
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all
    #          capabilities: [gpu]
    
    devices:
      - "/dev/dri:/dev/dri"
      
    volumes:
      - ./workspace:${WORKSPACE:-/workspace/}:rshared
      - ./config/authorized_keys:/root/.ssh/authorized_keys_mount
      - ./build/COPY_ROOT_1/opt/ai-dock/api-wrapper:/opt/ai-dock/api-wrapper
    ports:
        - ${SSH_PORT_HOST:-2222}:22
        - ${SERVICEPORTAL_PORT_HOST:-1111}:${SERVICEPORTAL_PORT_HOST:-1111}
        - ${COMFYUI_PORT_HOST:-8188}:${COMFYUI_PORT_HOST:-8188}
        - ${JUPYTER_PORT_HOST:-8888}:${JUPYTER_PORT_HOST:-8888}
        - ${SYNCTHING_UI_PORT_HOST:-8384}:${SYNCTHING_UI_PORT_HOST:-8384}
        - ${SYNCTHING_TRANSPORT_PORT_HOST:-22999}:${SYNCTHING_TRANSPORT_PORT_HOST:-22999}
   
    environment:
        - AUTO_UPDATE=${AUTO_UPDATE:-false}
        - DIRECT_ADDRESS=${DIRECT_ADDRESS:-127.0.0.1}
        - DIRECT_ADDRESS_GET_WAN=${DIRECT_ADDRESS_GET_WAN:-false}
        - WORKSPACE=${WORKSPACE:-/workspace}
        - WORKSPACE_SYNC=${WORKSPACE_SYNC:-false}
        - CF_TUNNEL_TOKEN=${CF_TUNNEL_TOKEN:-}
        - CF_QUICK_TUNNELS=${CF_QUICK_TUNNELS:-true}
        - CIVITAI_TOKEN=${CIVITAI_TOKEN:-}
        - HF_TOKEN=${HF_TOKEN:-}
        - WEB_ENABLE_AUTH=${WEB_ENABLE_AUTH:-true}
        - WEB_ENABLE_HTTPS=${WEB_ENABLE_HTTPS:-false}
        - WEB_USER=${WEB_USER:-user}
        - WEB_PASSWORD=${WEB_PASSWORD:-password}
        - SSH_PORT_HOST=${SSH_PORT_HOST:-2222}
        - SERVICEPORTAL_PORT_HOST=${SERVICEPORTAL_PORT_HOST:-1111}
        - SERVICEPORTAL_METRICS_PORT=${SERVICEPORTAL_METRICS_PORT:-21111}
        - SERVICEPORTAL_URL=${SERVICEPORTAL_URL:-}
        - COMFYUI_ARGS=${COMFYUI_ARGS:-}
        - COMFYUI_PORT_HOST=${COMFYUI_PORT_HOST:-8188}
        - COMFYUI_METRICS_PORT=${COMFYUI_METRICS_PORT:-28188}
        - COMFYUI_URL=${COMFYUI_URL:-}
        - JUPYTER_PORT_HOST=${JUPYTER_PORT_HOST:-8888}
        - JUPYTER_METRICS_PORT=${JUPYTER_METRICS_PORT:-28888}
        - JUPYTER_URL=${JUPYTER_URL:-}
        - SERVERLESS=${SERVERLESS:-false}
        - SYNCTHING_UI_PORT_HOST=${SYNCTHING_UI_PORT_HOST:-8384}
        - SYNCTHING_TRANSPORT_PORT_HOST=${SYNCTHING_TRANSPORT_PORT_HOST:-22999}
        - SYNCTHING_URL=${SYNCTHING_URL:-}